/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SolidermaRouteImport } from './routes/soliderma'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WoundCareRouteImport } from './routes/wound-care'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountCallbackRouteImport } from './routes/account.callback'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountLogoutRouteImport } from './routes/account.logout'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SolidermaRoute = SolidermaRouteImport.update({
  id: '/soliderma',
  path: '/soliderma',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WoundCareRoute = WoundCareRouteImport.update({
  id: '/wound-care',
  path: '/wound-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/account/callback',
  path: '/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLogoutRoute = AccountLogoutRouteImport.update({
  id: '/account/logout',
  path: '/account/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/soliderma': typeof SolidermaRoute
  '/terms': typeof TermsRoute
  '/wound-care': typeof WoundCareRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/soliderma': typeof SolidermaRoute
  '/terms': typeof TermsRoute
  '/wound-care': typeof WoundCareRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/soliderma': typeof SolidermaRoute
  '/terms': typeof TermsRoute
  '/wound-care': typeof WoundCareRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/certifications'
    | '/clinics'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shipping'
    | '/soliderma'
    | '/terms'
    | '/wound-care'
    | '/account/addresses'
    | '/account/callback'
    | '/account/login'
    | '/account/logout'
    | '/products/$slug'
    | '/account/'
    | '/products/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/certifications'
    | '/clinics'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shipping'
    | '/soliderma'
    | '/terms'
    | '/wound-care'
    | '/account/addresses'
    | '/account/callback'
    | '/account/login'
    | '/account/logout'
    | '/products/$slug'
    | '/account'
    | '/products'
    | '/account/orders/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/certifications'
    | '/clinics'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shipping'
    | '/soliderma'
    | '/terms'
    | '/wound-care'
    | '/account/addresses'
    | '/account/callback'
    | '/account/login'
    | '/account/logout'
    | '/products/$slug'
    | '/account/'
    | '/products/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CertificationsRoute: typeof CertificationsRoute
  ClinicsRoute: typeof ClinicsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingRoute: typeof ShippingRoute
  SolidermaRoute: typeof SolidermaRoute
  TermsRoute: typeof TermsRoute
  WoundCareRoute: typeof WoundCareRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCallbackRoute: typeof AccountCallbackRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountLogoutRoute: typeof AccountLogoutRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soliderma': {
      id: '/soliderma'
      path: '/soliderma'
      fullPath: '/soliderma'
      preLoaderRoute: typeof SolidermaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wound-care': {
      id: '/wound-care'
      path: '/wound-care'
      fullPath: '/wound-care'
      preLoaderRoute: typeof WoundCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/callback': {
      id: '/account/callback'
      path: '/account/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/logout': {
      id: '/account/logout'
      path: '/account/logout'
      fullPath: '/account/logout'
      preLoaderRoute: typeof AccountLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CertificationsRoute: CertificationsRoute,
  ClinicsRoute: ClinicsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingRoute: ShippingRoute,
  SolidermaRoute: SolidermaRoute,
  TermsRoute: TermsRoute,
  WoundCareRoute: WoundCareRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCallbackRoute: AccountCallbackRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountLogoutRoute: AccountLogoutRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
